# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1be17f09cc16b27329107d07baf94ef3468d45b0e4a6f7a02d56efa1412f36e328331055544465c570787ef0d64be8469c316881b9b867d3f421c582195ba91

test:
  secret_key_base: d9190ae5dcacdda5302293d44f01cbc598711aa0b5a4dd301c4463f9bae49ef37d0e09384a1bb6400921e33b0224007332c0f57cf3d73530c6a7779fbe9a22c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
